/*
 * memoryMap.h
 *
 *  Created on: Apr 29, 2025
 *      Author: luisv
 */

#ifndef EEPROM_MEMORYMAP_H_
#define EEPROM_MEMORYMAP_H_

typedef enum {
    VOLTAGE_CALIBRATION_MIN_0 = 0,
    VOLTAGE_CALIBRATION_MIN_1 = VOLTAGE_CALIBRATION_MIN_0 + 2,
    VOLTAGE_CALIBRATION_MIN_2 = VOLTAGE_CALIBRATION_MIN_1 + 2,
    VOLTAGE_CALIBRATION_MIN_3 = VOLTAGE_CALIBRATION_MIN_2 + 2,
    VOLTAGE_CALIBRATION_MIN_4 = VOLTAGE_CALIBRATION_MIN_3 + 2,
    VOLTAGE_CALIBRATION_MIN_5 = VOLTAGE_CALIBRATION_MIN_4 + 2,
    VOLTAGE_CALIBRATION_MIN_6 = VOLTAGE_CALIBRATION_MIN_5 + 2,
    VOLTAGE_CALIBRATION_MIN_7 = VOLTAGE_CALIBRATION_MIN_6 + 2,
    VOLTAGE_CALIBRATION_MIN_8 = VOLTAGE_CALIBRATION_MIN_7 + 2,
    VOLTAGE_CALIBRATION_MIN_9 = VOLTAGE_CALIBRATION_MIN_8 + 2,
    VOLTAGE_CALIBRATION_MAX_0 = VOLTAGE_CALIBRATION_MIN_9 + 2,
    VOLTAGE_CALIBRATION_MAX_1 = VOLTAGE_CALIBRATION_MAX_0 + 2,
    VOLTAGE_CALIBRATION_MAX_2 = VOLTAGE_CALIBRATION_MAX_1 + 2,
    VOLTAGE_CALIBRATION_MAX_3 = VOLTAGE_CALIBRATION_MAX_2 + 2,
    VOLTAGE_CALIBRATION_MAX_4 = VOLTAGE_CALIBRATION_MAX_3 + 2,
    VOLTAGE_CALIBRATION_MAX_5 = VOLTAGE_CALIBRATION_MAX_4 + 2,
    VOLTAGE_CALIBRATION_MAX_6 = VOLTAGE_CALIBRATION_MAX_5 + 2,
    VOLTAGE_CALIBRATION_MAX_7 = VOLTAGE_CALIBRATION_MAX_6 + 2,
    VOLTAGE_CALIBRATION_MAX_8 = VOLTAGE_CALIBRATION_MAX_7 + 2,
    VOLTAGE_CALIBRATION_MAX_9 = VOLTAGE_CALIBRATION_MAX_8 + 2,
    CURRENT_CALIBRATION_MIN_0 = VOLTAGE_CALIBRATION_MAX_9 + 2,
    CURRENT_CALIBRATION_MIN_1 = CURRENT_CALIBRATION_MIN_0 + 2,
    CURRENT_CALIBRATION_MIN_2 = CURRENT_CALIBRATION_MIN_1 + 2,
    CURRENT_CALIBRATION_MIN_3 = CURRENT_CALIBRATION_MIN_2 + 2,
    CURRENT_CALIBRATION_MIN_4 = CURRENT_CALIBRATION_MIN_3 + 2,
    CURRENT_CALIBRATION_MIN_5 = CURRENT_CALIBRATION_MIN_4 + 2,
    CURRENT_CALIBRATION_MIN_6 = CURRENT_CALIBRATION_MIN_5 + 2,
    CURRENT_CALIBRATION_MIN_7 = CURRENT_CALIBRATION_MIN_6 + 2,
    CURRENT_CALIBRATION_MIN_8 = CURRENT_CALIBRATION_MIN_7 + 2,
    CURRENT_CALIBRATION_MIN_9 = CURRENT_CALIBRATION_MIN_8 + 2,
    CURRENT_CALIBRATION_MAX_0 = CURRENT_CALIBRATION_MIN_9 + 2,
    CURRENT_CALIBRATION_MAX_1 = CURRENT_CALIBRATION_MAX_0 + 2,
    CURRENT_CALIBRATION_MAX_2 = CURRENT_CALIBRATION_MAX_1 + 2,
    CURRENT_CALIBRATION_MAX_3 = CURRENT_CALIBRATION_MAX_2 + 2,
    CURRENT_CALIBRATION_MAX_4 = CURRENT_CALIBRATION_MAX_3 + 2,
    CURRENT_CALIBRATION_MAX_5 = CURRENT_CALIBRATION_MAX_4 + 2,
    CURRENT_CALIBRATION_MAX_6 = CURRENT_CALIBRATION_MAX_5 + 2,
    CURRENT_CALIBRATION_MAX_7 = CURRENT_CALIBRATION_MAX_6 + 2,
    CURRENT_CALIBRATION_MAX_8 = CURRENT_CALIBRATION_MAX_7 + 2,
    CURRENT_CALIBRATION_MAX_9 = CURRENT_CALIBRATION_MAX_8 + 2,
} eepromAdresses_t;

#endif /* EEPROM_MEMORYMAP_H_ */
